services:
  upload-interface:
    build:
      context: ./upload-interface  
      dockerfile: Dockerfile        
    container_name: upload-interface
    ports:
      - "80:80"                     
    depends_on:
      - storage-service

  storage-service:
    build:
      context: ./storage-service  
      dockerfile: Dockerfile      
    container_name: storage-service
    ports:
      - "8000:80" # host port | container port
    depends_on:
      - db
      - minio
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/app1_db
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_ENDPOINT=http://minio:9000

  photo-display-service:
    build:
      context: ./photo-display
      dockerfile: Dockerfile      
    container_name: photo-display-service
    ports:
      - "5000:5000"
    depends_on:
      - db
      - minio
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/app2_db
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_ENDPOINT=http://minio:9000

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app1_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio: # for image storage
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
  minio_data: