# Generated by Django 4.1 on 2024-07-03 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime(2024, 7, 3, 12, 49, 26, 757110))),
            ],
            options={
                'db_table': 'Images',
            },
        ),
    ]
