# Generated by Django 4.2.13 on 2024-08-16 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage_service_app", "0002_alter_image_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 16, 11, 9, 51, 585137)
            ),
        ),
    ]
