apiVersion: v1
kind: Service
metadata:
  name: upload-interface-service
spec:
  selector:
    app: upload-interface
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
